import { relative } from 'node:path';

import type { ControllerIR } from '../analyzer/internal-representation';

type EmitAppGenOptions = {
  readonly distDir: string;
};

const stripTsExtension = (p: string): string => p.replace(/\.tsx?$/, '');

const toRelativeImport = (distDir: string, modulePath: string): string => {
  const rel = stripTsExtension(relative(distDir, modulePath));
  return rel.startsWith('.') ? rel : `./${rel}`;
};

const renderImport = (distDir: string, c: ControllerIR): string =>
  `import type { ${c.exportName} } from '${toRelativeImport(distDir, c.module)}';`;

const renderRouteLine = (c: ControllerIR, r: ControllerIR['routes'][number]): string =>
  `  Route<'${r.method}', '${r.fullPath}', typeof ${c.exportName}.prototype.${r.methodName}>,`;

export const emitAppGen = (
  controllers: readonly ControllerIR[],
  options: EmitAppGenOptions,
): string => {
  const imports = controllers.map((c) => renderImport(options.distDir, c)).join('\n');
  const routes = controllers.flatMap((c) => c.routes.map((r) => renderRouteLine(c, r)));

  return [
    '// THIS FILE IS GENERATED BY @zeltjs/openapi. DO NOT EDIT.',
    "import type { Route, BuildAppType } from '@zeltjs/openapi';",
    imports,
    '',
    'export type AppType = BuildAppType<[',
    ...routes,
    ']>;',
    '',
  ].join('\n');
};
