import { resolve } from 'node:path';

import { describe, expect, it } from 'vitest';

import { analyzeControllers } from '../analyzer/internal-representation';
import { createProject } from '../analyzer/project';

import { emitAppGen } from './app-gen';

const fixturePath = resolve(import.meta.dirname, '../analyzer/_fixtures/sample.controller.ts');

describe('emitAppGen', () => {
  const project = createProject({ controllerFiles: [fixturePath] });
  const ir = analyzeControllers(project, [{ filePath: fixturePath, exportName: 'UserController' }]);

  it('emits import type and Route entries with typeof Controller.prototype.method', () => {
    const out = emitAppGen(ir, { distDir: resolve(import.meta.dirname, '../../generated') });
    expect(out).toContain("import type { Route, BuildAppType } from '@koya/contract'");
    expect(out).toContain('UserController');
    expect(out).toMatch(/Route<'GET',\s*'\/users\/:id',\s*typeof UserController\.prototype\.show>/);
    expect(out).toMatch(/Route<'POST',\s*'\/users',\s*typeof UserController\.prototype\.create>/);
    expect(out).toContain('export type AppType = BuildAppType<[');
  });

  it('uses relative import path from distDir to controller module', () => {
    const out = emitAppGen(ir, { distDir: resolve(import.meta.dirname, '../../generated') });
    // distDir is contract/generated, fixture is at contract/src/analyzer/_fixtures/sample.controller.ts
    // Relative path from generated/ to src/analyzer/_fixtures/sample.controller is something like:
    //   ../src/analyzer/_fixtures/sample.controller
    expect(out).toMatch(/import type \{ UserController \} from '[^']+sample\.controller'/);
    expect(out).not.toMatch(/sample\.controller\.ts'/); // .ts extension stripped
  });

  it('header comment marks file as generated', () => {
    const out = emitAppGen(ir, { distDir: resolve(import.meta.dirname, '../../generated') });
    expect(out).toContain('GENERATED BY @koya/contract');
    expect(out).toContain('DO NOT EDIT');
  });
});
