name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels: ['feature', 'enhancement']
  - title: '🐛 Bug Fixes'
    labels: ['fix', 'bugfix']
    exclude-labels: ['feature', 'enhancement']
  - title: '📖 Documentation'
    labels: ['documentation']
    exclude-labels: ['feature', 'enhancement', 'fix', 'bugfix']
  - title: '🧹 Maintenance'
    labels: ['chore', 'maintenance']
    exclude-labels: ['feature', 'enhancement', 'fix', 'bugfix', 'documentation']
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
version-resolver:
  major:
    labels: ['breaking']
  minor:
    labels: ['feature', 'enhancement']
  patch:
    labels: ['fix', 'bugfix', 'chore']
  default: patch
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
