packages:
  - 'packages/*'
  - 'examples/*'
  - 'website'
ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - "@9wick/eslint-plugin-strict-type-rules"
  - better-sqlite3
  - esbuild
  - nx
