import { existsSync } from 'node:fs';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve, sep } from 'node:path';

// Substring shared by every zelt-generated file's header comment, regardless
// of comment syntax (`//`, `#`, ...). sweepStaleOutputs uses its presence as
// proof that a file outside `.zelt/` is safe to delete instead of handwritten.
export const GENERATED_FILE_HEADER_MARKER = 'Generated by zelt build. Do not edit.';

const ZELT_DIR_NAME = '.zelt';
const LEDGER_RELATIVE_PATH = join(ZELT_DIR_NAME, 'outputs.json');

// Written by mechanisms other than this ledger (this file, and `zelt graphql
// codegen`'s manifest) and must survive sweeps regardless of registration.
const NEVER_SWEEP_RELATIVE_PATHS: ReadonlySet<string> = new Set([
  LEDGER_RELATIVE_PATH,
  join(ZELT_DIR_NAME, 'graphql-codegen.json'),
]);

const ledgerPath = (cwd: string): string => resolve(cwd, LEDGER_RELATIVE_PATH);

const readLedger = async (cwd: string): Promise<readonly string[]> => {
  const path = ledgerPath(cwd);
  if (!existsSync(path)) return [];
  const raw = await readFile(path, 'utf8');
  const parsed: unknown = JSON.parse(raw);
  if (!Array.isArray(parsed)) return [];
  return parsed.flatMap((entry) => (typeof entry === 'string' ? [entry] : []));
};

const writeLedger = async (cwd: string, relativePaths: readonly string[]): Promise<void> => {
  const path = ledgerPath(cwd);
  await mkdir(dirname(path), { recursive: true });
  const sorted = [...relativePaths].sort();
  await writeFile(path, `${JSON.stringify(sorted, null, 2)}\n`, 'utf8');
};

const isWithinZeltDir = (cwd: string, absolutePath: string): boolean => {
  const rel = relative(resolve(cwd, ZELT_DIR_NAME), absolutePath);
  return rel !== '' && rel !== '..' && !rel.startsWith(`..${sep}`);
};

export type SweepStaleOutputsResult = {
  // Relative to cwd. `deleted` were removed; `skipped` were left in place
  // because they live outside `.zelt/` and lack the generated-file marker,
  // so they might be handwritten.
  readonly deleted: readonly string[];
  readonly skipped: readonly string[];
};

/** @throws {Error} */
export const sweepStaleOutputs = async (
  cwd: string,
  currentOutputs: readonly string[],
): Promise<SweepStaleOutputsResult> => {
  const toRelative = (absolutePath: string): string => relative(cwd, resolve(absolutePath));
  const currentRelative = new Set(
    currentOutputs.map(toRelative).filter((rel) => !NEVER_SWEEP_RELATIVE_PATHS.has(rel)),
  );
  const previousRelative = await readLedger(cwd);

  const deleted: string[] = [];
  const skipped: string[] = [];

  for (const rel of previousRelative) {
    if (currentRelative.has(rel) || NEVER_SWEEP_RELATIVE_PATHS.has(rel)) continue;

    const absolutePath = resolve(cwd, rel);
    if (!existsSync(absolutePath)) continue;

    if (!isWithinZeltDir(cwd, absolutePath)) {
      const content = await readFile(absolutePath, 'utf8');
      if (!content.includes(GENERATED_FILE_HEADER_MARKER)) {
        skipped.push(rel);
        continue;
      }
    }

    await rm(absolutePath, { force: true });
    deleted.push(rel);
  }

  await writeLedger(cwd, [...currentRelative]);

  return { deleted: deleted.sort(), skipped: skipped.sort() };
};
