import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { isZeltInvalidPrebuiltContributionError } from './cli.errors';
import type { PrebuiltContribution } from './config/config.types';
import { writePrebuiltModule } from './prebuilt-writer.lib';

const graphqlContribution: PrebuiltContribution = {
  feature: 'graphql',
  key: '/graphql',
  importPath: './graphql/graphql.runtime',
  exportName: 'graphqlPrebuilt',
};

describe('writePrebuiltModule', () => {
  let testDir: string;
  let outPath: string;

  beforeEach(async () => {
    testDir = join(tmpdir(), `zelt-cli-prebuilt-writer-test-${Date.now()}-${Math.random()}`);
    await mkdir(testDir, { recursive: true });
    outPath = join(testDir, '.zelt', 'prebuilt.ts');
  });

  afterEach(async () => {
    await rm(testDir, { recursive: true, force: true });
  });

  it('generates an empty features object when there are no contributions', async () => {
    const result = await writePrebuiltModule(testDir, []);

    expect(result).toEqual({ changed: true });
    const content = await readFile(outPath, 'utf8');
    expect(content).toBe(
      [
        '// Generated by zelt build. Do not edit.',
        "import type { ZeltPrebuilt } from '@zeltjs/core';",
        'export const zeltPrebuilt = {',
        '  version: 1,',
        '  features: {',
        '  },',
        '} satisfies ZeltPrebuilt;',
        '',
      ].join('\n'),
    );
  });

  it('generates a module for a single contribution', async () => {
    await writePrebuiltModule(testDir, [graphqlContribution]);

    const content = await readFile(outPath, 'utf8');
    expect(content).toBe(
      [
        '// Generated by zelt build. Do not edit.',
        "import type { ZeltPrebuilt } from '@zeltjs/core';",
        "import { graphqlPrebuilt as p0 } from './graphql/graphql.runtime';",
        'export const zeltPrebuilt = {',
        '  version: 1,',
        '  features: {',
        '    graphql: {',
        "      '/graphql': p0,",
        '    },',
        '  },',
        '} satisfies ZeltPrebuilt;',
        '',
      ].join('\n'),
    );
  });

  it('produces byte-identical output regardless of input order (feature/key sorted)', async () => {
    const a: PrebuiltContribution = {
      feature: 'openapi',
      key: '/openapi',
      importPath: './openapi/openapi.runtime',
      exportName: 'openapiPrebuilt',
    };
    const b: PrebuiltContribution = {
      feature: 'graphql',
      key: '/graphql-b',
      importPath: './graphql/graphql-b.runtime',
      exportName: 'graphqlPrebuilt',
    };
    const c: PrebuiltContribution = {
      feature: 'graphql',
      key: '/graphql-a',
      importPath: './graphql/graphql-a.runtime',
      exportName: 'graphqlPrebuilt',
    };

    await writePrebuiltModule(testDir, [a, b, c]);
    const contentOrder1 = await readFile(outPath, 'utf8');

    await rm(outPath, { force: true });
    await writePrebuiltModule(testDir, [c, a, b]);
    const contentOrder2 = await readFile(outPath, 'utf8');

    expect(contentOrder1).toBe(contentOrder2);
    expect(contentOrder1.indexOf("'/graphql-a'")).toBeLessThan(
      contentOrder1.indexOf("'/graphql-b'"),
    );
    expect(contentOrder1.indexOf('graphql:')).toBeLessThan(contentOrder1.indexOf('openapi:'));
  });

  it('throws on duplicate (feature, key) contributions', async () => {
    const duplicate: PrebuiltContribution = { ...graphqlContribution };

    await expect(writePrebuiltModule(testDir, [graphqlContribution, duplicate])).rejects.toThrow(
      /duplicate/i,
    );
  });

  it('throws on an invalid exportName that is not a valid JS identifier', async () => {
    const invalid: PrebuiltContribution = { ...graphqlContribution, exportName: 'not-valid' };

    await expect(writePrebuiltModule(testDir, [invalid])).rejects.toSatisfy(
      isZeltInvalidPrebuiltContributionError,
    );
  });

  it('throws on an invalid feature name that is not a valid JS identifier', async () => {
    const invalid: PrebuiltContribution = { ...graphqlContribution, feature: 'not valid' };

    await expect(writePrebuiltModule(testDir, [invalid])).rejects.toSatisfy(
      isZeltInvalidPrebuiltContributionError,
    );
  });

  it('throws on an importPath that is not a relative specifier', async () => {
    const invalid: PrebuiltContribution = { ...graphqlContribution, importPath: '@zeltjs/core' };

    await expect(writePrebuiltModule(testDir, [invalid])).rejects.toSatisfy(
      isZeltInvalidPrebuiltContributionError,
    );
  });

  it('throws on an empty key', async () => {
    const invalid: PrebuiltContribution = { ...graphqlContribution, key: '' };

    await expect(writePrebuiltModule(testDir, [invalid])).rejects.toSatisfy(
      isZeltInvalidPrebuiltContributionError,
    );
  });

  it('does not rewrite the file when content is unchanged', async () => {
    const first = await writePrebuiltModule(testDir, [graphqlContribution]);
    expect(first).toEqual({ changed: true });

    const second = await writePrebuiltModule(testDir, [graphqlContribution]);
    expect(second).toEqual({ changed: false });
  });

  it('rewrites the file when content changes', async () => {
    await writePrebuiltModule(testDir, [graphqlContribution]);

    const changedContribution: PrebuiltContribution = {
      ...graphqlContribution,
      exportName: 'otherExport',
    };
    const result = await writePrebuiltModule(testDir, [changedContribution]);

    expect(result).toEqual({ changed: true });
    const content = await readFile(outPath, 'utf8');
    expect(content).toContain('otherExport as p0');
  });

  it('creates the .zelt directory if it does not exist yet', async () => {
    await rm(join(testDir, '.zelt'), { recursive: true, force: true });

    await writePrebuiltModule(testDir, []);

    await expect(readFile(outPath, 'utf8')).resolves.toContain('features: {');
  });

  it('leaves a pre-existing unrelated file in .zelt untouched', async () => {
    await mkdir(join(testDir, '.zelt'), { recursive: true });
    await writeFile(join(testDir, '.zelt', 'other.txt'), 'keep-me');

    await writePrebuiltModule(testDir, []);

    await expect(readFile(join(testDir, '.zelt', 'other.txt'), 'utf8')).resolves.toBe('keep-me');
  });
});
